/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controller.LaberintoControlador;
import javax.swing.table.DefaultTableModel;
import Modelos.ModeloTablaLaberinto;
import java.awt.Color;
import java.util.Random;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author James
 */
public class Laberinto extends javax.swing.JFrame {

    private Object color;

    /**
     * Creates new form Laberinto
     */
    public Laberinto() {
        initComponents();
        seleccion();
    }

    ModeloTablaLaberinto ml = new ModeloTablaLaberinto();
    LaberintoControlador lc = new LaberintoControlador();

    private void cargarTabla() {
        LimpiarTabla();
        ml.getData(lc.caminosparedes(devolverF()));
        ml.setLaberinto(lc.caminosparedes(devolverF()));
        tbllaberinto.setModel(ml);
        tbllaberinto.updateUI();
    }

    private void LimpiarTabla() {
        DefaultTableModel limpiar = new DefaultTableModel();
        limpiar.setRowCount(0);
        limpiar.setColumnCount(devolverF());
        tbllaberinto.setModel(limpiar);
        tbllaberinto.updateUI();
    }

    private void seleccion() {
        cbxnumero.removeAllItems();
        Integer i = 0;
        for (i = 10; i <= 100; i++) {
            cbxnumero.addItem(i.toString());
        }
    }

    public int devolverF() {
        int devolver = Integer.parseInt(cbxnumero.getSelectedItem().toString());
        return devolver;
    }
    
    private void eys(){
        Random rand = new Random();
        Integer a = 2;
        Integer entrada = rand.nextInt(tbllaberinto.getRowCount());
        System.out.println(entrada);
        tbllaberinto.setValueAt(a, 0, entrada);
        entrada = rand.nextInt(tbllaberinto.getRowCount());
        System.out.println(entrada);
        tbllaberinto.setValueAt(a, tbllaberinto.getRowCount()-1, entrada);
        tbllaberinto.repaint();
        tbllaberinto.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtlaberinto = new javax.swing.JLabel();
        cbxnumero = new javax.swing.JComboBox<>();
        btngenerar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbllaberinto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtlaberinto.setBackground(new java.awt.Color(255, 255, 255));
        txtlaberinto.setForeground(new java.awt.Color(0, 0, 0));
        txtlaberinto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtlaberinto.setText("Laberinto");
        jPanel1.add(txtlaberinto);
        txtlaberinto.setBounds(270, 10, 100, 16);

        cbxnumero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxnumero);
        cbxnumero.setBounds(550, 40, 72, 22);

        btngenerar.setText("GENERAR");
        btngenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarActionPerformed(evt);
            }
        });
        jPanel1.add(btngenerar);
        btngenerar.setBounds(30, 40, 90, 23);

        jPanel2.setLayout(null);

        tbllaberinto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbllaberinto);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 720, 290);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 80, 740, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
        cargarTabla(); 
        eys();
    }//GEN-LAST:event_btngenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laberinto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngenerar;
    private javax.swing.JComboBox<String> cbxnumero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbllaberinto;
    private javax.swing.JLabel txtlaberinto;
    // End of variables declaration//GEN-END:variables
}
