/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controller.LaberintoControlador;
import javax.swing.table.DefaultTableModel;
import views.tables.ModeloTablaLaberinto;

/**
 *
 * @author James Pinto
 */
public class Laberinto extends javax.swing.JDialog {
    ModeloTablaLaberinto ml = new ModeloTablaLaberinto();
    LaberintoControlador lc = new LaberintoControlador();

    /**
     * Creates new form Laberinto
     */
    public Laberinto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        seleccion();
        cargarTabla();
    }
    
    private void cargarTabla(){
        ml.setLaberinto(lc.getMatriz());
        tbllaberinto.setModel(ml);
        tbllaberinto.updateUI();
    }
    
    private void seleccion () {
        cbxnumero.removeAllItems();
        Integer i = 0;
        for (i = 10; i <= 100; i++) {
            cbxnumero.addItem(i.toString());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btgenerar = new javax.swing.JButton();
        cbxnumero = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbllaberinto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LABERINTO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 800, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("TAMAÑO:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 10, 70, 20);

        btgenerar.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btgenerar.setForeground(new java.awt.Color(153, 0, 0));
        btgenerar.setText("GENERAR");
        btgenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgenerarActionPerformed(evt);
            }
        });
        jPanel2.add(btgenerar);
        btgenerar.setBounds(640, 10, 100, 30);

        cbxnumero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxnumero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxnumeroItemStateChanged(evt);
            }
        });
        cbxnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxnumeroActionPerformed(evt);
            }
        });
        jPanel2.add(cbxnumero);
        cbxnumero.setBounds(110, 10, 100, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 40, 800, 50);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        tbllaberinto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbllaberinto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbllaberinto);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 780, 450);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 100, 800, 470);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 820, 580);

        setSize(new java.awt.Dimension(833, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxnumeroActionPerformed
        // TODO add your handling code here:
        //int n = Integer.parseInt(cbxnumero.toString());
    }//GEN-LAST:event_cbxnumeroActionPerformed

    private void cbxnumeroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxnumeroItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxnumeroItemStateChanged

    private void btgenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgenerarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btgenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Laberinto dialog = new Laberinto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btgenerar;
    private javax.swing.JComboBox<String> cbxnumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbllaberinto;
    // End of variables declaration//GEN-END:variables
}
