/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import Modelos.ModeloTablaCasas;
import controller.CasasControlador;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author James
 */
public class ListaCasas extends javax.swing.JFrame {

    CasasControlador cc = new CasasControlador();
    ModeloTablaCasas mtc = new ModeloTablaCasas();

    /**
     * Creates new form ListaCasas
     */
    public ListaCasas() {
        initComponents();
        cargarTabla();
        cargarcbxD();
        cargarcbxP();
    }

    private void cargarTabla() {
        if (cc.listar() != null && cc.listar().length > 0) {
            mtc.setDatos(cc.listar());
            tblcasa.setModel(mtc);
            tblcasa.updateUI();
        }
    }

    private void cargarcbxD() {
        cbxdimensiones.removeAllItems();
        if (tblcasa.getColumnCount() == 5) {
            if (tblcasa.getRowCount() == 1) {
                cbxdimensiones.addItem((String)tblcasa.getValueAt(0, 3));
            } else {
                cbxdimensiones.addItem((String)tblcasa.getValueAt(0, 3));
                for (int i = 1; i < tblcasa.getRowCount()-1; i++) {
                    cbxdimensiones.addItem((String)tblcasa.getValueAt(i, 3));
                }
            }
        }
    }
    private void cargarcbxP() {
        cbxpisos.removeAllItems();
        if (tblcasa.getColumnCount() == 5) {
            if (tblcasa.getRowCount() == 1) {
                cbxpisos.addItem((String)tblcasa.getValueAt(0, 4));
            } else {
                cbxpisos.addItem((String)tblcasa.getValueAt(0, 4));
                for (int i = 1; i < tblcasa.getRowCount()-1; i++) {
                    cbxpisos.addItem((String)tblcasa.getValueAt(i, 4));
                }
            }
        }
    }
    private void filtrarResultados(){
        cargarTabla();
        int indexD = cbxdimensiones.getSelectedIndex();
        int indexP = cbxpisos.getSelectedIndex();
        int filas = tblcasa.getRowCount();
        String valor1 = cbxdimensiones.getItemAt(indexD);
        String valor2 = cbxpisos.getItemAt(indexP);
        DefaultTableModel cargar = new DefaultTableModel();
        cargar.setRowCount(0);
        cargar.addColumn(tblcasa.getColumnName(0));
        cargar.addColumn(tblcasa.getColumnName(1));
        cargar.addColumn(tblcasa.getColumnName(2));
        cargar.addColumn(tblcasa.getColumnName(3));
        cargar.addColumn(tblcasa.getColumnName(4));
        for (int i = 0; i <= filas - 1; i++) {
            String nombre1 = tblcasa.getValueAt(i, 3).toString();
            String nombre2 = tblcasa.getValueAt(i, 4).toString();
            if(nombre1.matches(valor1) && nombre2.matches(valor2)){
                String[] filtrar = {tblcasa.getValueAt(i, 0).toString(), tblcasa.getValueAt(i, 1).toString(),
                        tblcasa.getValueAt(i, 2).toString(), tblcasa.getValueAt(i, 3).toString(), 
                tblcasa.getValueAt(i, 4).toString()};
                    cargar.addRow(filtrar);
            } else {
                System.out.println(nombre1+" comparado con "+valor1);
                System.out.println(nombre2+" comparado con "+valor2);
            }
        }
        tblcasa.setModel(cargar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcasa = new javax.swing.JTable();
        cbxdimensiones = new javax.swing.JComboBox<>();
        cbxpisos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnfiltrar = new javax.swing.JButton();
        btnrefrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Casas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 10, 160, 16);

        jPanel2.setLayout(null);

        tblcasa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblcasa);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 660, 260);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 130, 680, 280);

        cbxdimensiones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxdimensiones);
        cbxdimensiones.setBounds(180, 40, 72, 22);

        cbxpisos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxpisos);
        cbxpisos.setBounds(180, 90, 72, 22);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nro pisos");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 90, 80, 16);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dimensiones");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 40, 80, 16);

        btnfiltrar.setText("FILTRAR");
        btnfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiltrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnfiltrar);
        btnfiltrar.setBounds(470, 40, 100, 23);

        btnrefrescar.setText("REFRESCAR");
        btnrefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefrescarActionPerformed(evt);
            }
        });
        jPanel1.add(btnrefrescar);
        btnrefrescar.setBounds(460, 90, 120, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiltrarActionPerformed
        filtrarResultados();
    }//GEN-LAST:event_btnfiltrarActionPerformed

    private void btnrefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefrescarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnrefrescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaCasas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfiltrar;
    private javax.swing.JButton btnrefrescar;
    private javax.swing.JComboBox<String> cbxdimensiones;
    private javax.swing.JComboBox<String> cbxpisos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcasa;
    // End of variables declaration//GEN-END:variables
}
