/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controller.LaberintoControlador;
import javax.swing.table.DefaultTableModel;
import Modelos.ModeloTablaLaberinto;
import Modelos.ModeloTablaMatriz;
import controller.MatrizControlador;

/**
 *
 * @author James
 */
public class Matriz extends javax.swing.JFrame {

    /**
     * Creates new form Laberinto
     */
    public Matriz() {
        initComponents();
    }

    ModeloTablaMatriz mtm = new ModeloTablaMatriz();
    MatrizControlador mc = new MatrizControlador();
     private void cargarTabla(){
         LimpiarTabla();
        mtm.getData(mc.llenar(Filas(), Columnas()));
        mtm.setLaberinto(mc.llenar(Filas(), Columnas()));
        tblmatriz.setModel(mtm);
        tblmatriz.updateUI();
         celdas();
    }
     private void LimpiarTabla(){
         DefaultTableModel limpiar = new DefaultTableModel();
         limpiar.setRowCount(0);
         limpiar.setColumnCount(Columnas());
         tblmatriz.setModel(limpiar);
         tblmatriz.updateUI();
     }
     
     private void celdas(){
         for(int i = 0; i<=tblmatriz.getRowCount();i++){
             tblmatriz.setEditingRow(i);
             for(int j = 0; j<=tblmatriz.getColumnCount();j++){
                 tblmatriz.setEditingColumn(j);
             }
         }
     }
     private int Filas(){
         int filas = Integer.parseInt(txtfilas.getText());
         return filas;
     }
     private int Columnas(){
         int columnas = Integer.parseInt(txtcolumnas.getText());
         return columnas;
     }
     
     private void eliminar(){
         int valor1 = Integer.parseInt(txteliminarnum.getText());
         int filas = tblmatriz.getRowCount();
         int columnas = tblmatriz.getColumnCount();
         int comparar;
         if(txteliminarnum.getText().isEmpty()){
             System.out.println("No se ha insertado texto");
             eliminarcbx();
         }
         for(int i = 0; i<=filas-1;i++){
             for(int j = 0; j<=columnas-1;j++){
                 comparar = Integer.parseInt(tblmatriz.getValueAt(i, j).toString());
                 if(valor1 == comparar || comparar == valor1){
                     tblmatriz.setValueAt(0, i, j);
                 } else {
                     System.out.println("saludotes");
                 }
             }
         }
         eliminarcbx();
         
     }
     private void eliminarcbx(){
         int index = cbxeliminartipo.getSelectedIndex();
         int filas = tblmatriz.getRowCount();
         int columnas = tblmatriz.getColumnCount();
         int comparar;
         for(int i = 0; i<=filas-1;i++){
             for(int j = 0; j<=columnas-1;j++){
                 comparar = Integer.parseInt(tblmatriz.getValueAt(i, j).toString());
                 if(index == 0){
                     System.out.println("saluditos");
                     break;
                 } else if (index == 1){ //par
                     if(comparar % 2 == 0){
                         tblmatriz.setValueAt(0, i, j);
                     } else {
                         System.out.println("Es inpar");
                     }
                 } else if (index == 2){ //inpar
                     if(comparar % 2 == 1){
                         tblmatriz.setValueAt(0, i, j);
                     } else {
                         System.out.println("Es par");
                     }
                 } else if (index == 3){ //primo
                     if(mc.verificarprimo(index) == true){
                         tblmatriz.setValueAt(0, i, j);
                     } else {
                         System.out.println("1 am y aun no duermo");
                     }
                     
                 }
             }    
         }
         
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtlaberinto = new javax.swing.JLabel();
        btngenerar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmatriz = new javax.swing.JTable();
        txtfilas = new javax.swing.JTextField();
        txtcolumnas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnlimpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txteliminarnum = new javax.swing.JTextField();
        cbxeliminartipo = new javax.swing.JComboBox<>();
        btneliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtlaberinto.setBackground(new java.awt.Color(255, 255, 255));
        txtlaberinto.setForeground(new java.awt.Color(0, 0, 0));
        txtlaberinto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtlaberinto.setText("Matriz");
        jPanel1.add(txtlaberinto);
        txtlaberinto.setBounds(310, 10, 100, 16);

        btngenerar.setText("GENERAR");
        btngenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarActionPerformed(evt);
            }
        });
        jPanel1.add(btngenerar);
        btngenerar.setBounds(70, 100, 90, 23);

        jPanel2.setLayout(null);

        tblmatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblmatriz);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 720, 250);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 190, 740, 270);
        jPanel1.add(txtfilas);
        txtfilas.setBounds(80, 40, 71, 22);
        jPanel1.add(txtcolumnas);
        txtcolumnas.setBounds(250, 40, 71, 22);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("COLUMNAS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 40, 70, 16);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("FILAS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 60, 16);

        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnlimpiar);
        btnlimpiar.setBounds(230, 100, 110, 23);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ELIMINAR TIPO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(450, 90, 100, 16);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ELIMINAR NUMERO");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 40, 120, 16);
        jPanel1.add(txteliminarnum);
        txteliminarnum.setBounds(570, 30, 100, 22);

        cbxeliminartipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nada", "par", "impar", "primo" }));
        jPanel1.add(cbxeliminartipo);
        cbxeliminartipo.setBounds(570, 90, 100, 22);

        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btneliminar);
        btneliminar.setBounds(480, 150, 140, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btngenerarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        LimpiarTabla();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btneliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matriz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btngenerar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JComboBox<String> cbxeliminartipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmatriz;
    private javax.swing.JTextField txtcolumnas;
    private javax.swing.JTextField txteliminarnum;
    private javax.swing.JTextField txtfilas;
    private javax.swing.JLabel txtlaberinto;
    // End of variables declaration//GEN-END:variables
}
